### ISSUE TITLE
Is the certificate of the server expired?

### ISSUE THREAD

**Issue by m4kvn** [bitrise-steplib/steps-create-install-page-qr-code#3]
Https access to the URL of the generated image could not be made.

**Comment by kameike** [comment]
<img width="457" alt="2018-07-05 11 54 52" src="https://user-images.githubusercontent.com/1224191/42300219-3f19d144-804a-11e8-90e7-15a88a7c70ed.png">

It is because the certificate for `api.qrserver.com` had been expired:sob:
